language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - pip install -r dev-requirements.txt
script:
  - make lint
  - make test
after_success:
  - coveralls
